# For more information: https://laravel.com/docs/sail
version: "3"
services:
#    dependencies:
#       image: laravelsail/php81-composer:latest
#      build: docker/laravel-dependencies-installer
#     volumes:
#        - "./site:/var/www/html"
    laravel.test:
        build:
            context: site/vendor/laravel/sail/runtimes/8.1
            dockerfile: Dockerfile
            args:
                WWWGROUP: "${WWWGROUP}"
        image: sail-8.1/app
        extra_hosts:
            - "host.docker.internal:host-gateway"
        ports:
            - "${APP_PORT:-80}:80"
            - "${VITE_PORT:-5173}:${VITE_PORT:-5173}"
        environment:
            WWWUSER: "${WWWUSER}"
            LARAVEL_SAIL: 1
            XDEBUG_MODE: "${SAIL_XDEBUG_MODE:-off}"
            XDEBUG_CONFIG: "${SAIL_XDEBUG_CONFIG:-client_host=host.docker.internal}"
        volumes:
            - "./site:/var/www/html"
        networks:
            - sail
        depends_on:
            - pgsql
            - dependencies
    pgsql:
        image: "postgres:14"
        ports:
            - "${FORWARD_DB_PORT:-5432}:5432"
        environment:
            PGPASSWORD: "${DB_PASSWORD:-secret}"
            POSTGRES_DB: "${DB_DATABASE}"
            POSTGRES_USER: "${DB_USERNAME}"
            POSTGRES_PASSWORD: "${DB_PASSWORD:-secret}"
        volumes:
            - "sail-pgsql:/var/lib/postgresql/data"
        networks:
            - sail
        healthcheck:
            test:
                [
                    "CMD",
                    "pg_isready",
                    "-q",
                    "-d",
                    "${DB_DATABASE}",
                    "-U",
                    "${DB_USERNAME}",
                ]
            retries: 3
            timeout: 5s
        depends_on:
            - dependencies
    pgadmin:
        container_name: pgadmin_container
        image: dpage/pgadmin4:6.15
        environment:
            PGADMIN_DEFAULT_EMAIL: postgres@local.int
            PGADMIN_DEFAULT_PASSWORD: "${DB_PASSWORD:-secret}"
            PG_DATABASE: megamania
            PG_USER: postgres
            PG_PASSWORD: "${DB_PASSWORD:-secret}"
        volumes:
            - ./docker/pgadmin:/root/.pgadmin
        ports:
            - 8081:80
        networks:
            - sail
        depends_on:
            - pgsql
networks:
    sail:
        driver: bridge
volumes:
    sail-pgsql:
        driver: local
